import React, { useEffect, useState } from 'react';
import { AlertTriangle, Check, ClipboardCheck, RefreshCw, ShieldCheck, X } from 'lucide-react';
import ApiService from '../services/api';

interface ReviewItem {
  id: string;
  raw_input: string;
  structured_intake: {
    symptoms: Array<{ name: string; duration: string; severity: string }>;
    missingInformation: string[];
    clinicianDraft: string;
    uncertainty: string;
  };
  safety_assessment: {
    urgency: 'immediate' | 'urgent' | 'routine';
    action: string;
    matchedRules: string[];
  };
  generation_mode: string;
  model: string | null;
  review_status: 'pending' | 'approved' | 'needs_changes';
  clinician_notes: string | null;
  created_at: string;
  patient_name: string;
  patient_email: string;
  reviewer_name: string | null;
}

const AIIntakeReviewQueue: React.FC = () => {
  const [items, setItems] = useState<ReviewItem[]>([]);
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(true);
  const [savingId, setSavingId] = useState('');
  const [error, setError] = useState('');

  const load = async () => {
    setIsLoading(true);
    setError('');
    try {
      const response = await ApiService.getAIIntakeReviews();
      if (!response.success) throw new Error(response.error || 'Could not load intake drafts.');
      setItems(response.data);
      setNotes(Object.fromEntries(response.data.map((item: ReviewItem) => [item.id, item.clinician_notes || ''])));
    } catch (requestError: any) {
      setError(requestError?.response?.data?.error || requestError.message || 'Could not load intake drafts.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const review = async (item: ReviewItem, status: 'approved' | 'needs_changes') => {
    setSavingId(item.id);
    setError('');
    try {
      await ApiService.reviewAIIntake(item.id, status, notes[item.id] || '');
      await load();
    } catch (requestError: any) {
      setError(requestError?.response?.data?.error || requestError.message || 'The review could not be saved.');
    } finally {
      setSavingId('');
    }
  };

  return (
    <section className="intake-review-queue">
      <header>
        <div>
          <span>HUMAN-IN-THE-LOOP WORKFLOW</span>
          <h2><ClipboardCheck size={25} /> AI Intake Review</h2>
          <p>Review AI-assisted drafts before they are treated as clinician-approved information. Safety urgency is generated by fixed rules.</p>
        </div>
        <button type="button" onClick={load} disabled={isLoading}><RefreshCw size={16} /> Refresh</button>
      </header>

      {error && <div className="review-error" role="alert">{error}</div>}
      {isLoading ? (
        <div className="review-empty">Loading intake drafts…</div>
      ) : items.length === 0 ? (
        <div className="review-empty">No intake drafts yet. Submit a fictional example from the Patient Portal first.</div>
      ) : (
        <div className="review-list">
          {items.map((item) => (
            <article className={`review-card status-${item.review_status}`} key={item.id}>
              <div className="review-card-top">
                <div>
                  <strong>{item.patient_name}</strong>
                  <span>{item.patient_email} · {new Date(item.created_at).toLocaleString()}</span>
                </div>
                <div className="review-badges">
                  <span className={`urgency-${item.safety_assessment.urgency}`}>
                    {item.safety_assessment.urgency === 'immediate' ? <AlertTriangle size={13} /> : <ShieldCheck size={13} />}
                    {item.safety_assessment.urgency}
                  </span>
                  <span>{item.generation_mode === 'openai_structured_output' ? `OpenAI · ${item.model}` : 'Free demo fallback'}</span>
                  <span>{item.review_status.replace('_', ' ')}</span>
                </div>
              </div>

              <div className="review-source"><span>PATIENT WORDS</span><p>{item.raw_input}</p></div>
              <div className="review-columns">
                <div>
                  <h3>Structured extraction</h3>
                  {item.structured_intake.symptoms.map((symptom, index) => (
                    <p key={`${symptom.name}-${index}`}><strong>{symptom.name}</strong><br /><small>{symptom.duration} · {symptom.severity}</small></p>
                  ))}
                </div>
                <div>
                  <h3>Deterministic safety result</h3>
                  <p>{item.safety_assessment.action}</p>
                  {item.safety_assessment.matchedRules.length > 0 && <small>{item.safety_assessment.matchedRules.join(' · ')}</small>}
                </div>
              </div>
              <div className="review-draft"><span>AI-ASSISTED CLINICIAN DRAFT</span><p>{item.structured_intake.clinicianDraft}</p></div>

              <label htmlFor={`review-note-${item.id}`}>Clinician notes</label>
              <textarea
                id={`review-note-${item.id}`}
                rows={3}
                value={notes[item.id] || ''}
                onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))}
                placeholder="Add corrections, missing context, or the reason for requesting changes."
              />
              <div className="review-actions">
                <button type="button" className="needs-changes" disabled={savingId === item.id} onClick={() => review(item, 'needs_changes')}><X size={16} /> Needs changes</button>
                <button type="button" className="approve" disabled={savingId === item.id} onClick={() => review(item, 'approved')}><Check size={16} /> Approve draft</button>
              </div>
            </article>
          ))}
        </div>
      )}
    </section>
  );
};

export default AIIntakeReviewQueue;
